apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: ufukcemdelice/udagram-api-feed:latest
        ports:
        - containerPort: 8100
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=4096"  
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
