apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ufukcemdelice/udagram-frontend:v3
        ports:
        - containerPort: 8100
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=4096" 
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1
