apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: ufukcemdelice/reverseproxy:v2
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=4096"  
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
